
[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
.env: line 1: HUGGING_FACE_HUB_TOKEN: command not found
.env: line 2: OPENAI_API_KEY: command not found
W1208 17:24:18.258000 3559074 torch/distributed/run.py:793] 
W1208 17:24:18.258000 3559074 torch/distributed/run.py:793] *****************************************
W1208 17:24:18.258000 3559074 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1208 17:24:18.258000 3559074 torch/distributed/run.py:793] *****************************************
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:15<00:15, 15.73s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:15<00:15, 15.87s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:15<00:15, 15.99s/it]Loading checkpoint shards:  50%|█████     | 1/2 [00:16<00:16, 16.04s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 10.77s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.52s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 10.82s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.59s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 10.82s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.60s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 10.92s/it]Loading checkpoint shards: 100%|██████████| 2/2 [00:23<00:00, 11.66s/it]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/scratch/mjd9571/VentureAI/fine_tuning/falcon7b.py", line 595, in <module>
[rank0]:     main()
[rank0]:   File "/scratch/mjd9571/VentureAI/fine_tuning/falcon7b.py", line 359, in main
[rank0]:     save_decoded_inputs(dataloader, tokenizer, num_samples=3, rank=local_rank)
[rank0]:   File "/scratch/mjd9571/VentureAI/fine_tuning/falcon7b.py", line 208, in save_decoded_inputs
[rank0]:     with open(decoded_path, "w") as f:
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: './trained_falcon7b_2/decoded_input.txt'
W1208 17:24:49.119000 3559074 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3559080 closing signal SIGTERM
W1208 17:24:49.120000 3559074 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3559081 closing signal SIGTERM
W1208 17:24:49.120000 3559074 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 3559082 closing signal SIGTERM
E1208 17:24:49.434000 3559074 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3559079) of binary: /scratch/mjd9571/VentureAI/myenv/bin/python
Traceback (most recent call last):
  File "/scratch/mjd9571/VentureAI/myenv/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/scratch/mjd9571/VentureAI/myenv/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/scratch/mjd9571/VentureAI/myenv/lib/python3.11/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/scratch/mjd9571/VentureAI/myenv/lib/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/scratch/mjd9571/VentureAI/myenv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/mjd9571/VentureAI/myenv/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
falcon7b.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-08_17:24:49
  host      : gr047.hpc.nyu.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3559079)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
